basic:
  label: 基础设置
  items:
    blog_domain:
      name: blog_domain
      label: 博客域名
      type: text
      default: "Localhost"
    journals_alias:
      name: journals_alias
      label: 日志别名
      type: text
      default: "日志"

highlight:
  label: 代码高亮
  items:
    highlight:
      name: highlight
      label: 代码高亮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    highlight_style:
      name: highlight_style
      label: 代码高亮样式
      type: select
      data-type: string
      default: 'monokai'
      options:
        - value: 'monokai'
          label: 'monokai'
        - value: 'default'
          label: 'default'
        - value: 'github'
          label: 'github'
        - value: 'idea'
          label: 'idea'
        - value: 'xcode'
          label: 'xcode'

beian:
  label: 备案信息
  items:
    show_icp:
      name: show_icp
      label: 显示ICP备案信息
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 显示
        - value: false
          label: 不显示
    icp_info:
      name: icp_info
      label: ICP备案信息
      type: text
      default: ""
    icp_url:
      name: icp_url
      label: ICP跳转网址
      type: text
      default: ""
    show_police:
      name: show_police
      label: 显示公安备案信息
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 显示
        - value: false
          label: 不现实
    police_info:
      name: police_info
      label: 公安备案信息
      type: text
      default: ""
    police_url:
      name: police_url
      label: 公安备跳转网址
      type: text
      default: ""